name: Update Catalog by downloading fresh OpenAPI spec

on:
  schedule:
    # Run daily at 12 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggers

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.9.13

jobs:
  scrape:
    name: Scrape LeafLink OpenAPI Spec
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required by peter-evans/create-pull-request
      pull-requests: write  # Required by peter-evans/create-pull-request
    steps:
    - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
      id: generate-token
      with:
        app-id: ${{ vars.RESERVOIR_GITHUB_APP_ID }}
        private-key: ${{ secrets.RESERVOIR_GITHUB_APP_PKEY }}

    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Set up uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        version: ${{ env.UV_VERSION }}

    - name: Run OpenAPI spec scraper
      run: uv run --group scrape python scripts/scrape_openapi_spec.py

    - name: Check Snaphot changes
      id: check_snapshot_changes
      continue-on-error: true
      run: git diff --quiet tests/__snapshots__

    - name: Open a Pull Request
      uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
      if: steps.check_snapshot_changes.outcome == 'failure'
      with:
        title: 'fix: Update catalog from fresh OpenAPI spec'
        body: |
          This PR was automatically generated by the OpenAPI spec scraper workflow.

          The LeafLink OpenAPI spec has been updated. Please review the changes and merge if everything looks good.
        commit-message: 'fix: Update OpenAPI spec'
        branch: update-openapi-spec
        delete-branch: true
        signoff: true
